### ISSUE TITLE
Personalize clusters with avatars.

### ISSUE THREAD

**Issue by creativecoder** [Automattic/automatticians-map#1]
Show clusters as a stack of avatars with the number of markers in the cluster.

**Comment by creativecoder** [comment]
Example: ![image](https://user-images.githubusercontent.com/1699996/38951450-4a93878c-430e-11e8-9c0f-7947e6e7091b.png)

**Comment by nb** [comment]
Showing both looks good.

Do you think we should try and show different avatars on top? Either between sessions or even in the same session? It doesn’t sound fair to either the arbitrary person shown on top or the ones hidden below them.

**Comment by creativecoder** [comment]
@nb I like the idea of rotating avatar images used for clusters. Since an important purpose of the map is exploration/discovery of various Automatticians, it might work to do it during the same page view, as a user zooms in and out of the map, to surface different faces as the clusters are redrawn.

I do want to be careful about keeping a sense of consistency in the UX, though, so will keep that in mind as I try this out. I think it would feel strange to switch images for clusters that stay in place as the map is panned, for example.

@evilluendas Anything to add about this?

**Comment by evilluendas** [comment]
> I do want to be careful about keeping a sense of consistency in the UX, though

I agree, I suspect that changing the main photo of a cluster as you zoom in or out will be very confusing as you lose an important point of reference in a critical moment. 

It could work as a "slideshow" though, so the photos stay for a few seconds and then fade into the next one. If the animation is slow and subtle and the clusters have a random delay so they don't change all at once, it may look very nice (specially if you're looking the map from a low zoom level, because it would feel very alive 👌).

In any case, I would definitely randomize the top avatars shown between sessions as the bare minimum.

**Comment by creativecoder** [comment]
Another UX issue I found while working on this was making sure that an avatar used for a cluster at a low zoom level consistently shows up at higher zoom levels, so that you can follow it all the way through the cluster hierarchy.

![cluster-example](https://user-images.githubusercontent.com/1699996/39088062-6e44dcd4-4571-11e8-848b-2ae33741a7ee.gif).

I broke out the slideshow feature into a separate issue, since that seems like an enhancement of the core functionality needed for clustering #8 .

Avatars used for clusters are now randomized in between page loads, but consistent while panning/zooming the map. I also refactored to assign cluster avatars while clusters are being built to shave off some ms from the JS boot time: https://automattic.github.io/automatticians-map/leaflet/.
