### ISSUE TITLE
Document updates to Automattician data source

### ISSUE THREAD

**Issue by creativecoder** [Automattic/automatticians-map#10]
- ~~Convert to geojson for compatibility with Leaflet.js~~ (using json or csv for smaller file size)
- Add role and bio information
- ~~Add id property with unique id~~ (gravatar id works pretty well for this purpose)
- Remove host/path and query string from gravatar urls--all we need is unique id

Update:

Here's the JSON format that will support the new map code.

```
[
  {
    "name": <string>
    "image": <string> (gravatar id, no host or query params needed)
    "role": <string>
    "bio": <string>
    "coordinates": [
      longitude <number>
      latitude <number>
    ]
  }
]
```

JSON will be requested via AJAX after `map.js` loads.

**Comment by nosolosw** [comment]
howdy @creativecoder I've got some ideas/questions for you to consider in case they're useful. Note that I don't know how we generate the data sources ([a11nLocations and a11nData](https://github.com/Automattic/automatticians-map/blob/gh-pages/leaflet/map.js#L1)) and haven't done any benchmarks to see if these improve performance in a noticeable way.

In order to improve fetching and parsing times, would it be worth:

* to merge locations and data files? In addition to size reduction by not having the name duplicated, could this have the added benefit of avoiding any conflicts when two automatticians share the name?
* using a csv-like text format such as `lat, lot, name, role, bio, gravatar` as the data source and convert it to GeoJSON with [some utility](https://www.npmjs.com/package/csv2geojson) in the client?
* instead of including the whole gravatar URL `https://2.gravatar.com/avatar/1faacb72c52f7d73bf6ad265a9434e26` use only the hash `1faacb72c52f7d73bf6ad265a9434e26` and create the URL dinamically client-side?
* reducing the point coordinates to N decimals? IIRC, 4 decimals were enough for city-level of positioning.
* delete the properties we don't use such as `pirate-ninja`, `cola`, `editor`, `keyboard`,`camera`, `browser`?
* remove from the generated data the automatticians that choose to be hidden from the map?

**Comment by creativecoder** [comment]
@nosolosw 

Thanks for these ideas! The existing `a11nLocations` and `a11nData` currently in this project were generated by quickly copying/modifying the source of the current page, so definitely need to be combined and optimized for production. (I don't have access to the original data or theme code, yet).

> to merge locations and data files?

Yes, absolutely. There's no need for two files.

> using a csv-like text format such as lat, lot, name, role, bio, gravatar as the data source and convert it to GeoJSON with some utility in the client?

Interesting idea, and I can see the benefit of shaving bytes as the number of individuals continues to grow. I think I'd rather serve as json, being a more standard client-side data format, and save some ms not having to do the conversion in js.

> instead of including the whole gravatar URL https://2.gravatar.com/avatar/1faacb72c52f7d73bf6ad265a9434e26 use only the hash 1faacb72c52f7d73bf6ad265a9434e26 and create the URL dinamically client-side?

Yes, let's do that.

> reducing the point coordinates to N decimals? IIRC, 4 decimals were enough for city-level of positioning.

Also makes sense, given we're limiting the location resolution to cities.

> delete the properties we don't use such as pirate-ninja, cola, editor, keyboard,camera, browser?

Agreed, let's only serve exactly what's needed for the map.

> remove from the generated data the automatticians that choose to be hidden from the map?

Yes, definitely want to respect that setting!

Also, I'm pretty sure the automattic.com theme us using `wp_localize_script` to inline the data on the page. I'd prefer an ajax or rest api url that returns the json so it can be retrieved in a separate request after initial page load and then parsed and added to the map async.

**Comment by creativecoder** [comment]
For now map code is set up to retrieve a JSON array of objects with the following properties:
```
coordinates: [lng, lat]
name
image (just the gravatar id, not the url or query string)
role
bio
```

Regarding the final format of data, @nosolosw pointed out that GeoJSON has a lot of redundant properties that unnecessarily increases the size of the data file.

So I wrote a quick script with the current data to generate different file formats to compare sizes.

Format|gzip|Size
---|---|---
geojson|no|345K
geojson|yes|121K
json|no|331K
json|yes|121K
csv|no|265K
csv|yes|115K

If we don't have a gzipped file, csv is very compelling for size savings, though will require some extra setup server and client side for creating and parsing that format. If we do have a gzipped file, the differences are much smaller, so I'd probably vote for json or geojson.

@nb Do you know (or know who to ask) if we can serve a json file gzipped from automattic.com?

**Comment by creativecoder** [comment]
Update: My understanding is that we can serve gzipped json, and that response can be dynamically generated or a static file. So for simplicity, let's go with the json structure we have now.
